micronaut:
  application:
    name: micronautKotlinMicroservice
  server:
    port: 8080
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
    endpoints:
      login:
        path: /auth/login
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/microservice
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 'root'
vertx:
  pg:
    client:
      port: 5432
      host: localhost
      database: microservice
      user: postgres
      password: root
      maxSize: 5
flyway:
  datasources: 
    default: 
      enabled: true
